<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE noteList
[
<!ELEMENT noteList (note+)>
<!ELEMENT note (to,from,heading,body)>
<!ELEMENT to (#PCDATA)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT heading (#PCDATA)>
<!ELEMENT body (#PCDATA)>
]
>
<noteList>
<note>
  <to>Tove</to>
  <from>Jani</from>
  <heading>Reminder</heading>
  <body>Don't forget me this weekend!</body>
</note>
<note>
  <to>David</to>
  <from>Russow</from>
  <heading>Reminder</heading>
  <body>Don't forget me this weekend!</body>
</note>
</noteList>
